
Charity.create(name: 'Mission Fresh Air', discription: 'It is our mission to show people across the United States what fresh air should really taste like. To accomplish this, we are delivering fresh Alaskan air in mason jars to people"s doorsteps. The goal of selling Alaskan air is to raise money for local clean air initiatives.', image: 'https://media.licdn.com/media-proxy/ext?w=542&h=358&f=&hash=3a5sO75p%2BYPOs58JZdqC2R8wJX8%3D&ora=1%2CaFBCTXdkRmpGL2lvQUFBPQ%2CxAVta9Er0Vinkhwfjw8177yE41y87UNCVordEGXyD3u0qYrdf3foecGNKOHyuV1FfigclAMzf_KhFTHiD5LoLo7sftQj3sG3I424ZxUBbFImi24')

Charity.create(name: 'Give A Meal', discription: 'We constantly hear about world hunger on the news and there are hundreds of organizations out there trying to solve this issue. But what can we do about local hunger? Hundreds of people in our own neighborhoods are hungry. These are people that have lived beside us for years, paid taxes, raised kids, and are now down on their luck. Here at Give A Meal we want to help these people in our backyards by giving them a free meal, from a local restaurant, for every $10 donated. Together, the goal is to give our neighbors some help and maybe change their luck a bit.', image: 'https://media.licdn.com/media-proxy/ext?w=543&h=384&f=&hash=%2B9NciSEvxotXQVojPwncvMRA1to%3D&ora=1%2CaFBCTXdkRmpGL2lvQUFBPQ%2CxAVta9Er0Vinkhwfjw8177yE41y87UNCVordEGXyD3u0qYrdf3DqLMTdfeeiuVtCKSsclFI1d_L6R2LnD5Lof9-7eNt5g5ewd424ZxUBbFImi24')

Charity.create(name: "American Red Cross", image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQAjcU7uQAzOAE5HN4O19_z2H9D-vT87kAheb23_mI1MWdM_1Cx", discription: "The American Red Cross (ARC), also known as the American National Red Cross, is a humanitarian organization that provides emergency assistance, disaster relief and education inside the United States. 
Today, in addition to domestic disaster relief, the American Red Cross offers services in five other areas: community services that help the needy; communications services and comfort for military members and their family members; the collection, processing and distribution of blood and blood products; educational programs on preparedness, health, and safety; and international relief and development programs.
The American Red Cross is a nationwide network of more than 650 chapters and 36 blood services regions dedicated to saving lives and helping people prepare for and respond to medical emergencies. Approximately 500,000 Red Cross volunteers, including FemaCorps and AmeriCorps members, and 30,000 employees annually mobilize relief to people affected by more than 67,000 disasters, train almost 12 million people in necessary medical skills and exchange more than a million emergency messages for U.S. military service personnel and their family members. The Red Cross is the largest supplier of blood and blood products to more than 3,000 hospitals nationally and also assists victims of international disasters and conflicts at locations worldwide. In 2006 the organization had over $6 billion in total revenues. Revenue from blood and blood products alone were over $2 billion.", small_image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQS4XdS5rhHNDfAZ80Wg_goI1mvxJ0A86PopzAZBsRsunijQCtw")


Charity.create(name: "World Wild Life (WWF)", image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRSlBQ-O7cXkccNamdTGsY0Dqq5dLcbF7XC9sOjz4sfXuB9mA63bQ", discription: "In 1961, a limited number of organizations around the world—such as the International Union for the Conservation of Nature and Natural Resources (IUCN) and The Conservation Foundation—were trying to meet conservation needs, but were desperately short of funds.
The first call for broad support was the Morges Manifesto, signed in 1961 by 16 of the world’s leading conservationists, including biologist and African wildlife enthusiast Sir Julian Huxley, IUCN vice president Sir Peter Scott and director-general of the British Nature Conservancy E. M. Nicholson. The Morges Manifesto stated that while the expertise to protect the world environment existed, the financial support to achieve this protection did not. The decision was made to establish World Wildlife Fund as an international fundraising organization to work in collaboration with existing conservation groups and bring substantial financial support to the conservation movement on a worldwide scale.", small_image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz1MhDX_FGcCsyW0_HMRBZMmdRx-w8L2Zwnhugj3fwIe75VgrgyQ")


Charity.create(name: "Amnesty International", image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS4-XrogM49pPV4B-2YoaunRJuV8omn-fuWSngoqzVYic40C4HsiQ", discription: "Amnesty International is a global movement of more than 7 million people who take injustice personally. We are campaigning for a world where human rights are enjoyed by all.
We are funded by members and people like you. We are independent of any political ideology, economic interest or religion. No government is beyond scrutiny. No situation is beyond hope. 
Few would have predicted when we started that torturers would become international outlaws. That most countries would abolish the death penalty. And seemingly untouchable dictators would be made to answer for their crimes.
We investigate and expose the facts, whenever and wherever abuses happen. 
We lobby governments, and other powerful groups such as companies. Making sure they keep their promises and respect international law. 
By telling the powerful stories of the people we work with, we mobilize millions of supporters around the world to campaign for change and to stand in defense of activists on the frontline. 
We support people to claim their rights through education and training.", small_image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSInbQDZZkioTBpH7yZwSQ8VPHOTjyT3NwHv306b6tSpWz5AaGjNQ")

Charity.create(name: "UNICEF", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmiPTtpSD-xZCd9M_MKBqR0bZGoeo0KLoKpIL2rsbkalBUPXjE", discription: "UNICEF was created by the United Nations General Assembly on December 11, 1946, to provide emergency food and healthcare to children in countries that had been devastated by World War II. Ludwik Rajchman, a Polish bacteriologist, is regarded as the founder of UNICEF and was its first chairman from 1946 to 1950.[3] In 1953, UNICEF became a permanent part of the United Nations System and its name was shortened from the original United Nations International Children's Emergency Fund but it has continued to be known by the popular acronym based on this previous title.
UNICEF relies on contributions from governments and private donors, UNICEF's total income for 2008 was $3,372,540,239.[4] Governments contribute two thirds of the organization's resources; private groups and some 6 million individuals contribute the rest through the National Committees. It is estimated that 91.8% of their revenue is distributed to Program Services.[5] UNICEF's programs emphasize developing community-level services to promote the health and well-being of children. UNICEF was awarded the Nobel Peace Prize in 1965 and the Prince of Asturias Award of Concord in 2006.
Most of UNICEF's work is in the field, with staff in over 190 countries and territories. More than 200 country offices carry out UNICEF's mission through a program developed with host governments. Seventeen regional offices provide technical assistance to country offices as needed.", small_image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQpboqmbHKt9ySeaCFlNmwPrOVq1Rnk1nxLNFfT-QsykhaGvOSzqQ")


Charity.create(name: "Feeding America", image: "https://upload.wikimedia.org/wikipedia/en/thumb/a/aa/Feeding_America_logo.svg/1280px-Feeding_America_logo.svg.png", discription: "In the late 1960s, John van Hengel, a retired businessman in Phoenix, Arizona began volunteering at a local soup kitchen, and began soliciting food donations for the kitchen. He ended up with far more food than the kitchen could use in its operations. Around this time, he spoke with one of the clients, who told him that she regularly fed her family with discarded items from the grocery store's garbage bins. She told him that the food quality was fine, but that there should be a place where unwanted food could be stored and later accessed by people who needed it, similar to how banks store money.
In August 2009, Columbia Records announced that all U.S. royalties from Bob Dylan's album Christmas in the Heart would be donated to Feeding America, in perpetuity.
There has been a rise in the numbers suffering from hunger since the 2008 financial crisis. In 2013, the USDA reported that about 49 million Americans were now facing the condition, about one in six of the population. In September, they launched Hunger Action Month, with events planned all over the nation, to raise awareness and get more Americans involved in helping out.", small_image: "http://images5.fanpop.com/image/photos/25300000/Feeding-America-s-Hunger-Action-Month-eliza-dushku-25345403-2560-1745.jpg")



Charity.create(name: "Food For The Poor", image: "http://donationsstatic.ebay.com/extend/logos/MF20016.jpg", discription: "Food For The Poor provides, as its main objective, nourishment to needy people. The organization also erects homes for homeless families, supplies medicine and health care in hospitals and clinics, subsidizes orphanages, teaches children and adults by providing knowledge and training for the careers.
Targeted crisis relief programs
In addition to its general community development and direct aid programs designed to reduce poverty and malnutrition, Food For The Poor provides targeted relief for humanitarian crises. On January 11, 2010, it announced initial success in introducing a new food source, the Basa fish, for the critically malnourished nation of Haiti.[3] Then, on January 13, 2010, it announced a major relief effort directed toward the people of the same nation to help recovery from the catastrophic January 12 earthquake which struck Port-au-Prince. According to its earthquake press release 'Food For The Poor (is) accepting: cash donations, canned meats, fish, condensed, evaporated and powdered milk, and water. The agency is immediately sending 400 containers of rice, beans, water, blankets, lumber and repairing zinc.'", small_image: "http://images.forbes.com/media/2010/11/16/1116_food-for-the-poor_397x278.jpg", small_image: "http://images.forbes.com/media/2010/11/16/1116_food-for-the-poor_397x278.jpg")


Charity.create(name: "American Cancer Society", image: "https://bootystrong.files.wordpress.com/2012/02/american-cancer-society-logo1.jpg", discription: "The society was originally founded on May 23, 1913 by 15 physicians and businessmen in New York City under the name American Society for the Control of Cancer (ASCC). The current name was adopted in 1944. According to Charity Navigator the ACS is one of the oldest and largest volunteer health organizations.[3]
At the time of founding, it was not considered appropriate to mention the word ‘cancer’ in public. Information concerning this illness was cloaked in a climate of fear and denial. Over 75,000 people died each year of cancer in just the United States. The top item on the founders’ agenda was to raise awareness of cancer, before any other progress could be made in funding research. Therefore a frenetic writing campaign was undertaken to educate doctors, nurses, patients and family members about cancer. Articles were written for popular magazines and professional journals. The ASCC undertook to publish their own journal, Campaign Notes, which was a monthly bulletin with information about cancer. They began recruiting doctors from all over the United States to help educate the public about cancer.", small_image: "http://www.gannett-cdn.com/-mm-/508f9116bd387982ab4b9346d766785e5302af24/c=93-0-1510-1066&r=x404&c=534x401/local/-/media/Westchester/Westchester/2014/03/22//1395540241000--Relay-for-Life-2jpg-20120522-2-.jpg")

Charity.create(name: "World Vision International", image: "http://www.theblaze.com/wp-content/uploads/2011/10/world-vision.jpg", discription: "Started in 1950 as World Vision Inc, the charity originally operated only in the United States but expanded to other countries in 1966.World Vision International was founded in 1977 by Walter Stanley Mooneyham the then president of World Vision.Today it is headquartered in Monrovia, California, in the same building as World Vision Inc. Mooneyham served as president of World Vision International until 1982 when he resigned after criticism within the International Board related to management style
During the 1990s, World Vision International began focusing on the needs of children who had been orphaned in Uganda, Romania, and Somalia in response to AIDS, neglect, and civil war, respectively. They began educating other African communities on AIDS after realizing its impact. They also joined the United Nations peacekeeping efforts to help those affected by civil war. World Vision also started to openly promote the international ban on land mines. In 1994 World Vision US moved to Washington State.
According to Forbes Magazine, as of December 2014, World Vision is the 11th largest charity in the United States with total revenue of over 981 million dollars.", small_image: "http://www.wvi.org/sites/default/files/styles/article_full/public/World%20Vision.jpg?itok=XxgxtIOg")



